# Generated by Django 5.1.2 on 2024-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="division",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
