# Generated by Django 5.1.2 on 2024-12-24 09:55

import django.db.models.deletion
import profile.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                (
                    "avatar",
                    models.ImageField(
                        default=profile.models.default_avatar, upload_to="avatars/"
                    ),
                ),
                (
                    "role",
                    models.TextField(
                        choices=[
                            ("admin", "Admin"),
                            ("customer", "Customer"),
                            ("provider", "Provider"),
                        ],
                        default="customer",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        related_query_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wishlist",
                    models.ManyToManyField(
                        blank=True,
                        related_name="wishlists",
                        related_query_name="wishlist",
                        to="product.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
                "db_table": "profiles",
                "ordering": ["user__date_joined"],
            },
        ),
    ]
