# Generated by Django 5.1.2 on 2024-12-08 04:13

import django.db.models.deletion
import orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("users", "0002_remove_customuser_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                related_query_name="order",
                to="users.profile",
                validators=[orders.models.is_customer],
            ),
        ),
    ]
