# Generated by Django 5.1.2 on 2024-12-17 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="user",
            new_name="profile",
        ),
    ]
