# Generated by Django 5.1.2 on 2024-12-24 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("discount", "0002_initial"),
        ("order", "0001_initial"),
        ("product", "0001_initial"),
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                related_query_name="order",
                to="profile.profile",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_codes",
            field=models.ManyToManyField(
                help_text="List of discount codes that are applied to this order",
                related_name="orders",
                related_query_name="order",
                to="discount.discountcode",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="item",
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                related_query_name="order",
                to="product.productvariant",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product_variant"), name="unique_order_item"
            ),
        ),
    ]
