# Generated by Django 5.1.2 on 2025-01-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="close_reason",
            new_name="cancel_reason",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROSSISSING", "Prossissing"),
                    ("CLOSED", "Closed"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
