# Generated by Django 5.1.2 on 2025-01-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_rename_close_reason_order_cancel_reason_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="profile",
        ),
    ]
