# Generated by Django 5.1.2 on 2024-12-30 12:11

import cart.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="item",
                to="cart.cart",
                validators=[cart.models.is_active_cart],
            ),
        ),
    ]
