# Generated by Django 5.1.2 on 2024-12-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_user"),
        ("users", "0003_delete_customuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name_plural": "Carts"},
        ),
        migrations.RenameField(
            model_name="cart",
            old_name="user",
            new_name="profile",
        ),
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.BooleanField(
                default=True,
                help_text="True if cart is active, False if cart is inactive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", True)),
                fields=("profile",),
                name="unique_active_cart",
            ),
        ),
        migrations.AlterModelTable(
            name="cart",
            table="cart",
        ),
    ]
