# Generated by Django 5.1.2 on 2024-12-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_cartitem_quantity"),
        (
            "product",
            "0009_alter_productvariant_color_alter_productvariant_size_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                fields=("cart", "product_variant"), name="unique_cart_item"
            ),
        ),
    ]
