# Generated by Django 5.1.2 on 2024-12-30 18:12

import cart.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_cartitem_unique_cart_item"),
        ("profile", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                related_query_name="cart",
                to="profile.profile",
                validators=[cart.models.is_customer],
            ),
        ),
    ]
