# Generated by Django 5.1.2 on 2025-01-07 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0006_alter_cart_customer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="note",
        ),
    ]
