# Generated by Django 5.1.2 on 2024-12-24 09:55

import django.db.models.deletion
import feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feedback", "0001_initial"),
        ("product", "0001_initial"),
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                related_query_name="feedback",
                to="profile.profile",
                validators=[feedback.models.is_customer],
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="product",
            field=models.ForeignKey(
                help_text="The product that the feedback is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                related_query_name="feedback",
                to="product.product",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.UniqueConstraint(
                fields=("customer", "product"), name="unique_feedback"
            ),
        ),
    ]
