# Generated by Django 5.1.2 on 2024-12-08 04:13

import django.db.models.deletion
import feedbacks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0001_initial"),
        ("users", "0002_remove_customuser_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                related_query_name="feedback",
                to="users.profile",
                validators=[feedbacks.models.is_customer],
            ),
        ),
    ]
