# Generated by Django 5.1.2 on 2024-12-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0002_alter_feedback_customer"),
        ("products", "0001_initial"),
        ("users", "0003_delete_customuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["-rate"],
                "verbose_name": "Feedback",
                "verbose_name_plural": "Feedbacks",
            },
        ),
        migrations.AddConstraint(
            model_name="feedback",
            constraint=models.UniqueConstraint(
                fields=("customer", "product"), name="unique_feedback"
            ),
        ),
    ]
