# Generated by Django 5.1.2 on 2024-12-06 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "avatar",
                    models.ImageField(default="default.jpg", upload_to="avatars/"),
                ),
                (
                    "role",
                    models.TextField(
                        choices=[
                            ("admin", "Admin"),
                            ("customer", "Customer"),
                            ("provider", "Provider"),
                        ],
                        default="customer",
                        max_length=16,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["user__date_joined"],
            },
        ),
    ]
