# Generated by Django 5.1.2 on 2024-12-08 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_cart_user"),
        ("feedbacks", "0002_alter_feedback_customer"),
        ("orders", "0002_alter_order_user"),
        ("users", "0002_remove_customuser_user_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
