# Generated by Django 5.1.2 on 2024-12-24 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                related_query_name="product",
                to="profile.profile",
                verbose_name="product provider",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="products",
            field=models.ManyToManyField(
                related_name="collections",
                related_query_name="collection",
                to="product.product",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.color"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.img"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.product"
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="size",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.size"
            ),
        ),
    ]
