# Generated by Django 5.1.2 on 2024-12-28 20:36

import django.db.models.deletion
import product.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_initial"),
        ("profile", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="img",
            name="alt",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="img",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="img",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                related_query_name="product",
                to="profile.profile",
                validators=[product.models.product.is_provider],
                verbose_name="product provider",
            ),
        ),
    ]
