# Generated by Django 5.1.2 on 2024-12-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_img_alt_alter_img_height_alter_img_width_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="img",
            name="height",
        ),
        migrations.RemoveField(
            model_name="img",
            name="width",
        ),
    ]
