# Generated by Django 5.1.2 on 2024-12-29 07:40

import product.models.color
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_remove_img_height_remove_img_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="color1_value",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                validators=[product.models.color.validate_color],
                verbose_name="First color value",
            ),
        ),
    ]
