# Generated by Django 5.1.2 on 2024-12-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_color_color1_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="quantity",
            field=models.PositiveBigIntegerField(),
        ),
    ]
