# Generated by Django 5.1.2 on 2024-12-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_alter_productvariant_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="quantity",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
