# Generated by Django 5.1.2 on 2024-12-29 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_productvariant_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                related_query_name="variant",
                to="product.color",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="variants",
                related_query_name="variant",
                to="product.img",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                related_query_name="variant",
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                related_query_name="variant",
                to="product.size",
            ),
        ),
    ]
