# Generated by Django 5.1.2 on 2025-02-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0009_alter_productvariant_color_alter_productvariant_size_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="division",
            options={
                "ordering": ["name"],
                "verbose_name": "Division",
                "verbose_name_plural": "Divisions",
            },
        ),
        migrations.AlterField(
            model_name="division",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
