# Generated by Django 5.1.2 on 2025-02-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_division_options_alter_division_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["division__name", "name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterUniqueTogether(
            name="category",
            unique_together={("division", "name")},
        ),
    ]
