# Generated by Django 5.1.2 on 2025-02-21 21:33

import django.core.validators
import product.models.size
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_alter_category_unique_together_alter_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="color",
            options={
                "ordering": ["color1_name"],
                "verbose_name": "Color",
                "verbose_name_plural": "Colors",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="size",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Size",
                "verbose_name_plural": "Sizes",
            },
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="cost",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The cost on the seller.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The price for the customer.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="sort_order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(
                max_length=3,
                unique=True,
                validators=[product.models.size.validate_size],
            ),
        ),
    ]
