# Generated by Django 5.1.2 on 2024-12-06 02:36

import datetime
import discounts.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        help_text="a string representing the reason of the discount,e.g. eid discount, black friday, special offer for Eisha ,etc.",
                        max_length=255,
                    ),
                ),
                (
                    "percentage",
                    models.FloatField(
                        help_text="discount percentage as a float number between 0 and 100",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("start", models.DateTimeField(default=datetime.datetime.now)),
                ("end", models.DateTimeField(default=discounts.models.end_date)),
            ],
            options={
                "verbose_name": "Discount",
                "verbose_name_plural": "Discounts",
                "db_table": "discounts",
            },
        ),
    ]
