# Generated by Django 5.1.2 on 2024-12-08 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="percentage",
        ),
        migrations.AddField(
            model_name="discount",
            name="amount",
            field=models.PositiveIntegerField(
                default=10,
                help_text="discount amount as a fixed number",
                validators=[django.core.validators.MinValueValidator(10)],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discount",
            name="code",
            field=models.CharField(
                default="iposajdipoasj",
                help_text="a unique code for the discount",
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
