# Generated by Django 5.1.2 on 2024-11-02 17:57

import stock.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="image",
        ),
        migrations.AddField(
            model_name="productcolor",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=stock.models.image_path
            ),
        ),
    ]
