# Generated by Django 5.1.2 on 2024-12-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_rename_color_1_productcolor_color1_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcolor",
            name="color1_name",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
