# Generated by Django 5.1.2 on 2024-12-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("stock", "0003_alter_productcolor_color1_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcolor",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="colors",
                related_query_name="color",
                to="products.product",
            ),
        ),
    ]
