# Generated by Django 5.1.2 on 2024-12-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_alter_productcolor_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcolor",
            options={"verbose_name": "Color", "verbose_name_plural": "Colors"},
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={
                "ordering": ["price"],
                "verbose_name": "Stock",
                "verbose_name_plural": "Stocks",
            },
        ),
    ]
