# Generated by Django 5.1.2 on 2024-12-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("stock", "0005_alter_productcolor_options_alter_stock_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductColor",
            new_name="Color",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="product_colored",
            new_name="color",
        ),
        migrations.AlterModelTable(
            name="color",
            table="colors",
        ),
    ]
